organization_repositories:
  - name: "voxsamrt-service-api"
    description: "Fronted main app repository"
    visibility: "private"

  - name: "voxsmart-service-ui"
    description: "Backend core Framework team"
    visibility: "private"

  - name: "voxsmart-service-sdk"
    description: "Backend core Framework team"
    visibility: "public"
