organization_repositories:
  - name: "voxsamrt-service-api"
    description: "Fronted main app repository"
    private: true

  - name: "voxsmart-service-ui"
    description: "Backend core Framework team"
    private: true

  - name: "voxsmart-service-sdk"
    description: "Backend core Framework team"
    private: false
