organization_repositories:
  - name: "voxsmart-service-api"
    description: "Main business Service API"
    visibility: private

  - name: "voxsmart-service-ui"
    description: "Front Service UI"
    visibility: private

  - name: "voxsmart-service-sdk"
    description: "Backend core SDK Framework"
    visibility: public
