teams:
  frontend_team:
    name: "frontend_team"
    description: "Team for frontend developers"
    privacy: "closed"
    members:
      - username: "erasmolpa"
        role: "member"

  backend_team:
    name: "backend_team"
    description: "Team for backend developers"
    privacy: "closed"
    members:
      - username: "erasmodominguezdc"
        role: "member"
      - username: "erasmolpa"
        role: "member"
